name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php-version:
          - 8.2
          - 8.3

    steps:
      - name: Configure Git to avoid issues with line endings
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1, assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On

      - name: Install dependencies with Composer
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

      - name: Running PHP-CS-Fixer in Linter Mode
        run: composer run-script php-cs-fixer -- --dry-run --show-progress=dots --using-cache=no --verbose

      - name: Running PHPStan
        run: composer run-script phpstan

      - name: Running test-suites
        run: composer run-script test
